name: Build Android APK

on:
  push:
    branches: [ "main" ] # Robot jalan tiap kamu simpan kode di branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil Kode dari Repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Proses Build APK
        run: |
          gradle assembleDebug

      - name: Upload Hasil APK
        uses: actions/upload-artifact@v3
        with:
          name: Aplikasi-Rycl-Debug
          path: app/build/outputs/apk/debug/*.apk
          
